apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}
  labels:
    app: {{ .Release.Name }}
    chart: {{ .Chart.Name }}-{{ .Chart.Version }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
spec:
  {{- $env := .Values.global.environment }}
  {{- $config := index .Values.environments $env }}
  replicas: {{ $config.replicaCount }}
  selector:
    matchLabels:
      app: {{ .Release.Name }}
      release: {{ .Release.Name }}
  template:
    metadata:
      labels:
        app: {{ .Release.Name }}
        release: {{ .Release.Name }}
      annotations:
        {{- with .Values.podAnnotations }}
        {{- toYaml . | nindent 8 }}
        {{- end }}
        prometheus.io/scrape: "{{ .Values.metrics.enabled }}"
        prometheus.io/path: "{{ .Values.metrics.path }}"
        prometheus.io/port: "{{ .Values.metrics.port }}"
    spec:
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      containers:
        - name: {{ .Chart.Name }}
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          env:
            - name: LOG_LEVEL
              value: {{ $config.logLevel }}
            - name: PORT
              value: "8080"
          ports:
            - name: http
              containerPort: 8080
              protocol: TCP
          livenessProbe:
            {{- toYaml .Values.livenessProbe | nindent 12 }}
          readinessProbe:
            {{- toYaml .Values.readinessProbe | nindent 12 }}
          resources:
            {{- toYaml $config.resources | nindent 12 }}
          volumeMounts:
            - name: tmp
              mountPath: /tmp
      {{- if .Values.logShipping.enabled }}
        - name: log-shipping
          image: {{ .Values.logShipping.image }}
          volumeMounts:
            - name: config
              mountPath: /fluent-bit/etc/
            - name: logs
              mountPath: /logs
          resources:
            requests:
              cpu: 100m
              memory: 128Mi
            limits:
              cpu: 200m
              memory: 256Mi
      {{- end }}
      volumes:
        - name: tmp
          emptyDir: {}
        {{- if .Values.logShipping.enabled }}
        - name: config
          configMap:
            name: {{ .Values.logShipping.configMap.name }}
        - name: logs
          emptyDir: {}
        {{- end }}