{{- $env := .Values.global.environment }}
{{- $config := index .Values.environments $env }}
{{- if $config.ingress.enabled }}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ .Release.Name }}
  labels:
    app: {{ .Release.Name }}
    chart: {{ .Chart.Name }}-{{ .Chart.Version }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
  {{- with $config.ingress.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  rules:
    - host: {{ $config.ingress.host }}
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: {{ .Release.Name }}
                port:
                  name: http
  {{- if eq $env "prod" }}
  tls:
    - hosts:
        - {{ $config.ingress.host }}
      secretName: {{ .Release.Name }}-tls
  {{- end }}
{{- end }}