#!/usr/bin/env bash

# Source the colors utility
SCRIPT_DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"
source "$SCRIPT_DIR/colors.sh"

print_yellow "AWS CLI Version: aws-cli/2.11.3 Python/3.9.11 Linux/5.15.0-1031-aws exe/x86_64.ubuntu.22 prompt/off"
print_yellow "Region: us-east-1"
print_yellow "Operation: DescribeInstances"
print_yellow "Service: EC2"
print_yellow "Timestamp: 2023-07-12T14:23:45Z"
print_yellow "Request ID: a1b2c3d4-5678-90ab-cdef-EXAMPLE11111"
echo ""
print_error "An error occurred (ThrottlingException) when calling the DescribeInstances operation: Rate exceeded"
print_error "Rate Exceeded: please retry after 1.0 seconds"
echo ""
print_yellow "API Call Details:"
print_detail "{"
print_detail "  \"Error\": {"
print_detail "    \"Code\": \"ThrottlingException\","
print_detail "    \"Message\": \"Rate exceeded\","
print_detail "    \"Type\": \"Sender\","
print_detail "    \"RequestId\": \"a1b2c3d4-5678-90ab-cdef-EXAMPLE11111\""
print_detail "  },"
print_detail "  \"ResponseMetadata\": {"
print_detail "    \"RequestId\": \"a1b2c3d4-5678-90ab-cdef-EXAMPLE11111\","
print_detail "    \"HTTPStatusCode\": 400,"
print_detail "    \"HTTPHeaders\": {"
print_detail "      \"x-amzn-requestid\": \"a1b2c3d4-5678-90ab-cdef-EXAMPLE11111\","
print_detail "      \"content-type\": \"application/x-amz-json-1.1\","
print_detail "      \"content-length\": \"318\","
print_detail "      \"date\": \"Wed, 12 Jul 2023 14:23:45 GMT\""
print_detail "    },"
print_detail "    \"RetryAttempts\": 3"
print_detail "  }"
print_detail "}"
echo ""
print_yellow "Service Quotas:"
print_detail "- EC2 API Rate: 100 requests per second"
print_detail "- Current usage: ~120 requests per second"
echo ""
print_yellow "Recommended actions:"
print_yellow "1. Implement exponential backoff with jitter in your API calls"
print_yellow "2. Reduce the frequency of API calls"
print_yellow "3. Request a service quota increase if needed"
print_yellow "4. Use AWS SDK with built-in retry mechanisms"
