#!/usr/bin/env bash
# Source the colors utility
SCRIPT_DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"
source "$SCRIPT_DIR/colors.sh"
# Source the colors utility
SCRIPT_DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"
source "$SCRIPT_DIR/colors.sh"

print_yellow "Kubernetes cluster: production-cluster"
print_yellow "Namespace: backend"
print_yellow "Pod: order-service-7d8fb9c46-2xvp4"
print_yellow "Container: order-service"
print_yellow "Node: worker-node-05"
print_yellow "Timestamp: 2023-08-18T22:14:37Z"
print_yellow ""
print_error "memory cgroup out of memory: Kill process 42 (java) score 1000 or sacrifice child"
print_error "Killed process 42 (java) total-vm:4196348kB, anon-rss:2097152kB, file-rss:0kB, shmem-rss:0kB"
print_yellow ""
print_yellow "Container Status:"
print_detail "Name:          order-service"
print_detail "State:         Terminated"
print_detail "  Reason:      OOMKilled"
print_detail "  Exit Code:   137"
print_detail "  Started:     Thu, 18 Aug 2023 22:10:15 +0000"
print_detail "  Finished:    Thu, 18 Aug 2023 22:14:37 +0000"
print_detail "Ready:         False"
print_detail "Restart Count: 5"
print_detail "Limits:"
print_detail "  cpu:     1"
print_detail "  memory:  2Gi"
print_detail "Requests:"
print_detail "  cpu:     500m"
print_detail "  memory:  1Gi"
print_yellow ""
print_yellow "Last log entries before OOM:"
print_detail "2023-08-18T22:14:35.123Z INFO  [OrderProcessor] - Processing batch of 1000 orders"
print_detail "2023-08-18T22:14:36.456Z INFO  [OrderProcessor] - Memory usage high: 1950MB / 2048MB"
print_detail "2023-08-18T22:14:36.789Z WARN  [OrderProcessor] - GC overhead limit exceeded"
print_detail "2023-08-18T22:14:37.012Z ERROR [OrderProcessor] - Java heap space"
print_yellow ""
print_yellow "Recommended actions:"
print_yellow "1. Increase container memory limit (current: 2Gi)"
print_yellow "2. Optimize application memory usage"
print_yellow "3. Configure JVM heap settings appropriately"
print_yellow "4. Add memory monitoring and alerts"
print_yellow "5. Consider implementing circuit breakers for high load"