#!/usr/bin/env bash
# Source the colors utility
SCRIPT_DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"
source "$SCRIPT_DIR/colors.sh"
# Source the colors utility
SCRIPT_DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"
source "$SCRIPT_DIR/colors.sh"

print_yellow "Kubernetes cluster: staging-cluster"
print_yellow "Namespace: frontend"
print_yellow "Pod: user-interface-9c5d7b845-8fqp2"
print_yellow "Container: nodejs-app"
print_yellow "Node: worker-node-03"
print_yellow "Timestamp: 2023-09-22T15:42:19Z"
print_yellow ""
print_error "memory cgroup out of memory: Kill process 78 (node) score 1000 or sacrifice child"
print_error "Killed process 78 (node) total-vm:3145728kB, anon-rss:1572864kB, file-rss:0kB, shmem-rss:0kB"
print_yellow ""
print_yellow "Container Status:"
print_detail "Name:          nodejs-app"
print_detail "State:         Terminated"
print_detail "  Reason:      OOMKilled"
print_detail "  Exit Code:   137"
print_detail "  Started:     Fri, 22 Sep 2023 15:35:42 +0000"
print_detail "  Finished:    Fri, 22 Sep 2023 15:42:19 +0000"
print_detail "Ready:         False"
print_detail "Restart Count: 3"
print_detail "Limits:"
print_detail "  cpu:     500m"
print_detail "  memory:  1.5Gi"
print_detail "Requests:"
print_detail "  cpu:     250m"
print_detail "  memory:  750Mi"
print_yellow ""
print_yellow "Last log entries before OOM:"
print_detail "2023-09-22T15:42:16.234Z INFO  [Server] - Handling high traffic spike - 500 concurrent users"
print_detail "2023-09-22T15:42:17.567Z INFO  [Server] - Memory usage critical: 1420MB / 1536MB"
print_detail "2023-09-22T15:42:18.123Z WARN  [Server] - V8 garbage collection taking too long"
print_detail "2023-09-22T15:42:18.890Z ERROR [Server] - JavaScript heap out of memory"
print_yellow ""
print_yellow "Recommended actions:"
print_yellow "1. Increase container memory limit (current: 1.5Gi)"
print_yellow "2. Enable Node.js memory limits with --max-old-space-size"
print_yellow "3. Implement memory leak detection and monitoring"
print_yellow "4. Add rate limiting for API endpoints"
print_yellow "5. Consider implementing server-side caching"