#!/usr/bin/env bash
# Source the colors utility
SCRIPT_DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"
source "$SCRIPT_DIR/colors.sh"
# Source the colors utility
SCRIPT_DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"
source "$SCRIPT_DIR/colors.sh"

print_yellow "Attempting to merge feature/auth-service into main..."
print_yellow ""
print_yellow "From github.com:company/infrastructure-repo"
print_yellow " * branch            main       -> FETCH_HEAD"
print_yellow "Auto-merging main.tf"
print_error "CONFLICT (content): Merge conflict in main.tf"
print_yellow "Auto-merging modules/networking/variables.tf"
print_yellow "Auto-merging modules/database/main.tf"
print_error "CONFLICT (content): Merge conflict in modules/database/main.tf"
print_yellow "Automatic merge failed; fix conflicts and then commit the result."
print_yellow ""
print_yellow "Conflicting files:"
print_detail "  main.tf"
print_detail "  modules/database/main.tf"
print_yellow ""
print_yellow "Conflict in main.tf:"
print_detail "<<<<<<< HEAD"
print_detail "module \"vpc\" {"
print_detail "  source = \"./modules/networking\""
print_detail "  vpc_cidr = \"10.0.0.0/16\""
print_detail "  environment = \"production\""
print_detail "  region = \"us-west-2\""
print_detail "======="
print_detail "module \"vpc\" {"
print_detail "  source = \"./modules/networking\""
print_detail "  vpc_cidr = \"10.0.0.0/16\""
print_detail "  environment = \"production\""
print_detail "  region = \"us-east-1\""
echo -e "\e[90m  availability_zones = [\"us-east-1a\", \"us-east-1b\", \"us-east-1c\"]\e[0m"
print_detail ">>>>>>> feature/auth-service"
print_yellow ""
print_error "Error: Failed to push to protected branch 'main'. Merge conflicts must be resolved first."
print_yellow "Remote: error: GH006: Protected branch update failed for refs/heads/main."
print_yellow "Remote: error: Required status check \"ci/jenkins\" is failing."
print_yellow " ! [remote rejected] HEAD -> main (protected branch hook declined)"
print_yellow "error: failed to push some refs to 'git@github.com:company/infrastructure-repo.git'"