#!/usr/bin/env bash
# Source the colors utility
SCRIPT_DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"
source "$SCRIPT_DIR/colors.sh"
# Source the colors utility
SCRIPT_DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"
source "$SCRIPT_DIR/colors.sh"

print_yellow "Release \"monitoring-stack\" has been upgraded. Happy Helming!"
print_yellow "NAME: monitoring-stack"
print_yellow "LAST DEPLOYED: Fri Oct 13 09:15:22 2023"
print_yellow "NAMESPACE: monitoring"
print_yellow "STATUS: deployed"
print_yellow "REVISION: 7"
print_yellow "TEST SUITE: None"
print_yellow "NOTES:"
print_yellow "1. Access Grafana by running:"
print_yellow "   kubectl port-forward svc/monitoring-stack-grafana 3000:80 -n monitoring"
print_yellow "   Then open http://localhost:3000 and login with admin/admin"
print_yellow ""
print_yellow "Upgrading monitoring-stack to version 3.4.2..."
print_yellow ""
print_error "Error: YAML parse error on charts/monitoring-stack/templates/configmap.yaml: mapping values are not allowed in this context"
print_yellow ""
print_yellow "Error details:"
print_detail "  File: charts/monitoring-stack/templates/configmap.yaml"
print_detail "  Line: 27"
print_detail "  Content: '  alerting.yml: {"
print_detail "  Context:"
print_detail "    25:  prometheus.yml: |"
print_detail "    26:    {{ .Values.prometheus.config | nindent 4 }}"
print_detail "    27:  alerting.yml: {"
print_detail "    28:    {{ toYaml .Values.alerting | nindent 4 }}"
print_detail "    29:  }"
print_yellow ""
print_yellow "Helm upgrade failed. Rolling back to previous version..."
print_yellow "Rollback successful. Previous version 3.3.9 is active."