#!/usr/bin/env bash
# Source the colors utility
SCRIPT_DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"
source "$SCRIPT_DIR/colors.sh"
# Source the colors utility
SCRIPT_DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"
source "$SCRIPT_DIR/colors.sh"

print_yellow "Release \"api-gateway\" has been upgraded. Happy Helming!"
print_yellow "NAME: api-gateway"
print_yellow "LAST DEPLOYED: Tue Jun 20 15:32:47 2023"
print_yellow "NAMESPACE: services"
print_yellow "STATUS: deployed"
print_yellow "REVISION: 4"
print_yellow "TEST SUITE: None"
print_yellow "NOTES:"
print_yellow "1. Get the application URL by running these commands:"
echo -e "\e[33m  export POD_NAME=\$(kubectl get pods --namespace services -l \"app.kubernetes.io/name=api-gateway,app.kubernetes.io/instance=api-gateway\" -o jsonpath=\"{.items[0].metadata.name}\")\e[0m"
print_yellow "  export CONTAINER_PORT=\$(kubectl get pod --namespace services \$POD_NAME -o jsonpath=\"{.spec.containers[0].ports[0].containerPort}\")"
echo -e "\e[33m  kubectl --namespace services port-forward \$POD_NAME 8080:\$CONTAINER_PORT\e[0m"
print_yellow "  echo \"Visit http://127.0.0.1:8080 to use your application\""
print_yellow ""
print_yellow "Upgrading api-gateway to version 2.1.0..."
print_yellow ""
print_error "Error: YAML parse error on charts/api-gateway/templates/deployment.yaml: error converting YAML to JSON: yaml: line 42: did not find expected key"
print_yellow ""
print_yellow "Error details:"
print_detail "  File: charts/api-gateway/templates/deployment.yaml"
print_detail "  Line: 42"
print_detail "  Content: '      containers:'"
print_detail "  Context:"
print_detail "    40:    app.kubernetes.io/instance: {{ .Release.Name }}"
print_detail "    41:  spec:"
print_detail "    42:      containers:"
print_detail "    43:        name: {{ .Chart.Name }}"
print_detail "    44:        image: \"{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}\""
print_yellow ""
print_yellow "Helm upgrade failed. Rolling back to previous version..."