#!/usr/bin/env bash
# Source the colors utility
SCRIPT_DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"
source "$SCRIPT_DIR/colors.sh"
# Source the colors utility
SCRIPT_DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"
source "$SCRIPT_DIR/colors.sh"

print_yellow "MySQL Client: mysql Ver 5.7.38 for debian-linux-gnu on x86_64 (MySQL Community Server)"
print_yellow "Connecting to database: customer_data"
print_yellow "Host: mysql-replica-2.us-west.rds.amazonaws.com"
print_yellow "User: web_app"
print_yellow ""
print_error "ERROR 1040 (HY000): Too many connections"
print_yellow ""
print_yellow "MySQL Connection Status:"
print_detail "+----------------------+-------+"
print_detail "| Variable_name        | Value |"
print_detail "+----------------------+-------+"
print_detail "| max_connections      | 1000  |"
print_detail "| Threads_connected    | 1000  |"
print_detail "| Threads_running      | 956   |"
print_detail "| Connection_errors    | 5782  |"
print_detail "+----------------------+-------+"
print_yellow ""
print_yellow "Process list (top 5 by time):"
print_detail "+--------+---------------+---------------------+---------------+------+----------+------------------+"
print_detail "| Id     | User          | Host                | db            | Time | State    | Query            |"
print_detail "+--------+---------------+---------------------+---------------+------+----------+------------------+"
print_detail "| 583921 | etl_user      | 172.31.45.67:43215  | customer_data | 3542 | Copying  | INSERT INTO...   |"
print_detail "| 583762 | web_app       | 172.31.12.18:51432  | customer_data | 2871 | Sending  | SELECT * FROM... |"
print_detail "| 583814 | web_app       | 172.31.12.19:52178  | customer_data | 2654 | Sending  | SELECT * FROM... |"
print_detail "| 583899 | web_app       | 172.31.12.20:49876  | customer_data | 2341 | Sending  | SELECT * FROM... |"
print_detail "| 583945 | admin_user    | 172.31.5.10:60234   | NULL          | 1982 | Query    | SHOW PROCESSLIST |"
print_detail "+--------+---------------+---------------------+---------------+------+----------+------------------+"
print_yellow ""
print_yellow "Possible causes:"
print_yellow "1. Traffic spike during peak hours"
print_yellow "2. ETL processes consuming too many connections"
print_yellow "3. Connection pooling not properly configured"
print_yellow "4. Slow queries causing connection pileup"
print_yellow ""
print_yellow "Recommended actions:"
print_yellow "1. Implement connection pooling or review current settings"
print_yellow "2. Schedule ETL jobs during off-peak hours"
print_yellow "3. Optimize slow queries identified in process list"
print_yellow "4. Consider read replicas to distribute database load"
print_yellow "5. Monitor connection usage with CloudWatch alarms"