#!/usr/bin/env bash
# Source the colors utility
SCRIPT_DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"
source "$SCRIPT_DIR/colors.sh"
# Source the colors utility
SCRIPT_DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"
source "$SCRIPT_DIR/colors.sh"

print_yellow "MySQL Client: mysql Ver 8.0.32 for Linux on x86_64 (MySQL Community Server - GPL)"
print_yellow "Connecting to database: production_db"
print_yellow "Host: db-prod-master.internal.example.com"
print_yellow "User: app_service"
print_yellow ""
print_error "ERROR 1040 (HY000): Too many connections"
print_yellow ""
print_yellow "MySQL Connection Status:"
print_detail "+----------------------+-------+"
print_detail "| Variable_name        | Value |"
print_detail "+----------------------+-------+"
print_detail "| max_connections      | 500   |"
print_detail "| Threads_connected    | 500   |"
print_detail "| Threads_running      | 487   |"
print_detail "| Connection_errors    | 2143  |"
print_detail "+----------------------+-------+"
print_yellow ""
print_yellow "Process list (top 5 by time):"
print_detail "+--------+---------------+---------------------+-----------+------+----------+------------------+"
print_detail "| Id     | User          | Host                | db        | Time | State    | Query            |"
print_detail "+--------+---------------+---------------------+-----------+------+----------+------------------+"
print_detail "| 429892 | reporting_svc | 10.0.12.53:52341    | analytics | 1243 | Sending  | SELECT * FROM... |"
print_detail "| 429768 | app_service   | 10.0.14.27:39158    | prod_db   | 985  | Sending  | SELECT * FROM... |"
print_detail "| 429801 | app_service   | 10.0.14.28:41022    | prod_db   | 912  | Sending  | SELECT * FROM... |"
print_detail "| 429845 | app_service   | 10.0.14.30:52998    | prod_db   | 845  | Sending  | SELECT * FROM... |"
print_detail "| 429921 | backup_user   | 10.0.10.5:60122     | NULL      | 782  | Copying  | NULL             |"
print_detail "+--------+---------------+---------------------+-----------+------+----------+------------------+"
print_yellow ""
print_yellow "Possible causes:"
print_yellow "1. Connection pool misconfiguration"
print_yellow "2. Connection leaks in application code"
print_yellow "3. Long-running queries not being closed"
print_yellow "4. Database server under high load"
print_yellow ""
print_yellow "Recommended actions:"
print_yellow "1. Check application connection pooling settings"
print_yellow "2. Increase max_connections parameter if appropriate"
print_yellow "3. Kill long-running queries if they are not critical"
print_yellow "4. Restart the application with proper connection handling"