#!/usr/bin/env bash
# Source the colors utility
SCRIPT_DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"
source "$SCRIPT_DIR/colors.sh"
# Source the colors utility
SCRIPT_DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"
source "$SCRIPT_DIR/colors.sh"

print_yellow "Initializing the backend..."
print_yellow "Successfully configured the backend \"s3\"! Terraform will automatically"
print_yellow "use this backend unless the backend configuration changes."
print_yellow ""
print_yellow "Initializing provider plugins..."
print_yellow "- Finding hashicorp/aws versions matching \"~> 3.0\"..."
print_yellow "- Installing hashicorp/aws v3.76.1..."
print_yellow "- Installed hashicorp/aws v3.76.1 (signed by HashiCorp)"
print_yellow ""
print_yellow "Terraform has been successfully initialized!"
print_yellow ""
print_yellow "Terraform will perform the following actions:"
print_yellow ""
print_yellow "Plan: 3 to add, 0 to change, 0 to destroy."
print_yellow ""
print_yellow "Do you want to perform these actions?"
print_yellow "  Terraform will perform the actions described above."
print_yellow "  Only 'yes' will be accepted to approve."
print_yellow ""
print_yellow "  Enter a value: yes"
print_yellow ""
print_error "Error: Error acquiring the state lock"
print_yellow ""
print_yellow "Error message: ConditionalCheckFailedException: The conditional request failed"
print_yellow "Lock Info:"
print_yellow "  ID:        fd4cfc3e-2c8f-89a1-7c5f-8c3b9d24f31c"
print_yellow "  Path:      terraform-states/production/network/terraform.tfstate"
print_yellow "  Operation: apply"
print_yellow "  Who:       jenkins@build-server-01"
print_yellow "  Version:   1.3.7"
print_yellow "  Created:   2023-06-15 09:42:31.645789 +0000 UTC"
print_yellow "  Info:      "
print_yellow ""
print_yellow "Terraform acquires a state lock to protect the state from being written"
print_yellow "by multiple users at the same time. Please resolve the issue above and try"
print_yellow "again. For most commands, you can disable locking with the '-lock=false'"
print_yellow "flag, but this is not recommended."