#!/usr/bin/env bash
# Source the colors utility
SCRIPT_DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"
source "$SCRIPT_DIR/colors.sh"
# Source the colors utility
SCRIPT_DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"
source "$SCRIPT_DIR/colors.sh"

print_yellow "Initializing the backend..."
print_yellow "Successfully configured the backend \"gcs\"! Terraform will automatically"
print_yellow "use this backend unless the backend configuration changes."
print_yellow ""
print_yellow "Initializing provider plugins..."
print_yellow "- Finding hashicorp/google versions matching \"~> 4.0\"..."
print_yellow "- Installing hashicorp/google v4.52.0..."
print_yellow "- Installed hashicorp/google v4.52.0 (signed by HashiCorp)"
print_yellow ""
print_yellow "Terraform has been successfully initialized!"
print_yellow ""
print_yellow "Terraform will perform the following actions:"
print_yellow ""
print_yellow "Plan: 5 to add, 2 to change, 1 to destroy."
print_yellow ""
print_yellow "Do you want to perform these actions?"
print_yellow "  Terraform will perform the actions described above."
print_yellow "  Only 'yes' will be accepted to approve."
print_yellow ""
print_yellow "  Enter a value: yes"
print_yellow ""
print_error "Error: Error acquiring the state lock"
print_yellow ""
print_yellow "Error message: Error acquiring lock with ID 7a9b2c3d-4e5f-6789-0a1b-2c3d4e5f6789"
print_yellow "Lock Info:"
print_yellow "  ID:        7a9b2c3d-4e5f-6789-0a1b-2c3d4e5f6789"
print_yellow "  Path:      gs://terraform-states/staging/database/terraform.tfstate"
print_yellow "  Operation: apply"
print_yellow "  Who:       github-actions@runner-abc123"
print_yellow "  Version:   1.4.2"
print_yellow "  Created:   2023-09-22 14:18:45.123456 +0000 UTC"
print_yellow "  Info:      retrying in 5s"
print_yellow ""
print_yellow "Terraform acquires a state lock to protect the state from being written"
print_yellow "by multiple users at the same time. Please resolve the issue above and try"
print_yellow "again. For most commands, you can disable locking with the '-lock=false'"
print_yellow "flag, but this is not recommended."