apiVersion: apps/v1
kind: Deployment
metadata:
  name: loadgen
  namespace: monitoring
  labels:
    app: loadgen
spec:
  replicas: 1
  selector:
    matchLabels:
      app: loadgen
  template:
    metadata:
      labels:
        app: loadgen
      annotations:
        prometheus.io/scrape: "true"
        prometheus.io/port: "8080"
    spec:
      containers:
      - name: loadgen
        image: prom/prometheus:latest
        args:
        - "--config.file=/etc/prometheus/prometheus.yml"
        - "--storage.tsdb.path=/prometheus"
        - "--web.listen-address=:8080"
        - "--web.enable-lifecycle"
        ports:
        - containerPort: 8080
        volumeMounts:
        - name: config-volume
          mountPath: /etc/prometheus
      volumes:
      - name: config-volume
        configMap:
          name: loadgen-config
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: loadgen-config
  namespace: monitoring
data:
  prometheus.yml: |
    global:
      scrape_interval: 15s
      evaluation_interval: 15s
    
    scrape_configs:
      - job_name: 'dummy'
        static_configs:
          - targets: ['localhost:8080']
        metrics_path: /metrics