apiVersion: v1
kind: ConfigMap
metadata:
  name: prometheus-config
  namespace: monitoring
data:
  prometheus.yml: |
    global:
      scrape_interval: 15s
      evaluation_interval: 15s
    
    rule_files:
      - /etc/prometheus/rules/*.yml
    
    scrape_configs:
      - job_name: 'prometheus'
        static_configs:
          - targets: ['localhost:9090']
      
      - job_name: 'kubernetes-pods'
        kubernetes_sd_configs:
          - role: pod
        relabel_configs:
          - source_labels: [__meta_kubernetes_pod_annotation_prometheus_io_scrape]
            action: keep
            regex: true
          - source_labels: [__meta_kubernetes_pod_annotation_prometheus_io_path]
            action: replace
            target_label: __metrics_path__
            regex: (.+)
          - source_labels: [__address__, __meta_kubernetes_pod_annotation_prometheus_io_port]
            action: replace
            regex: ([^:]+)(?::\d+)?;(\d+)
            replacement: $1:$2
            target_label: __address__
          - action: labelmap
            regex: __meta_kubernetes_pod_label_(.+)
          - source_labels: [__meta_kubernetes_namespace]
            action: replace
            target_label: kubernetes_namespace
          - source_labels: [__meta_kubernetes_pod_name]
            action: replace
            target_label: kubernetes_pod_name

  rules/alerts.yml: |
    groups:
    - name: ALERTS_ALWAYS_ON
      rules:
      - alert: DiskFull
        expr: vector(1)
        for: 10s
        labels:
          severity: critical
        annotations:
          summary: "Disk Full on {{ $labels.instance }}"
          description: "Disk usage is over 90% on {{ $labels.instance }}"
      
      - alert: HighCpuUsage
        expr: vector(1)
        for: 10s
        labels:
          severity: critical
        annotations:
          summary: "High CPU Usage on {{ $labels.instance }}"
          description: "CPU usage is over 90% on {{ $labels.instance }}"
      
      - alert: K8sCrashLoop
        expr: vector(1)
        for: 10s
        labels:
          severity: critical
        annotations:
          summary: "Pod in CrashLoopBackOff state"
          description: "Pod {{ $labels.pod }} in namespace {{ $labels.namespace }} is in CrashLoopBackOff state"
      
      - alert: MemoryExhausted
        expr: vector(1)
        for: 10s
        labels:
          severity: critical
        annotations:
          summary: "Memory Exhausted on {{ $labels.instance }}"
          description: "Memory usage is over 95% on {{ $labels.instance }}"
      
      - alert: NetworkLatencyHigh
        expr: vector(1)
        for: 10s
        labels:
          severity: critical
        annotations:
          summary: "High Network Latency"
          description: "Network latency is above threshold for service {{ $labels.service }}"
      
      - alert: DatabaseConnectionsFull
        expr: vector(1)
        for: 10s
        labels:
          severity: critical
        annotations:
          summary: "Database Connections Full"
          description: "Database {{ $labels.database }} has reached maximum connections"
      
      - alert: ServiceUnavailable
        expr: vector(1)
        for: 10s
        labels:
          severity: critical
        annotations:
          summary: "Service Unavailable"
          description: "Service {{ $labels.service }} is unavailable"
      
      - alert: CertificateExpiringSoon
        expr: vector(1)
        for: 10s
        labels:
          severity: critical
        annotations:
          summary: "TLS Certificate Expiring Soon"
          description: "TLS Certificate for {{ $labels.domain }} will expire in less than 7 days"

  datasources/datasource.yaml: |
    apiVersion: 1
    
    datasources:
      - name: Prometheus
        type: prometheus
        access: proxy
        url: http://prometheus.monitoring:9090
        isDefault: true
        editable: false

  dashboards/dashboard.json: |
    {
      "annotations": {
        "list": [
          {
            "builtIn": 1,
            "datasource": {
              "type": "grafana",
              "uid": "-- Grafana --"
            },
            "enable": true,
            "hide": true,
            "iconColor": "rgba(0, 211, 255, 1)",
            "name": "Annotations & Alerts",
            "type": "dashboard"
          }
        ]
      },
      "editable": true,
      "fiscalYearStartMonth": 0,
      "graphTooltip": 0,
      "id": 1,
      "links": [],
      "liveNow": false,
      "panels": [
        {
          "datasource": {
            "type": "prometheus",
            "uid": "PBFA97CFB590B2093"
          },
          "fieldConfig": {
            "defaults": {
              "color": {
                "mode": "palette-classic"
              },
              "custom": {
                "axisCenteredZero": false,
                "axisColorMode": "text",
                "axisLabel": "",
                "axisPlacement": "auto",
                "barAlignment": 0,
                "drawStyle": "bars",
                "fillOpacity": 100,
                "gradientMode": "none",
                "hideFrom": {
                  "legend": false,
                  "tooltip": false,
                  "viz": false
                },
                "lineInterpolation": "linear",
                "lineWidth": 1,
                "pointSize": 5,
                "scaleDistribution": {
                  "type": "linear"
                },
                "showPoints": "auto",
                "spanNulls": false,
                "stacking": {
                  "group": "A",
                  "mode": "none"
                },
                "thresholdsStyle": {
                  "mode": "off"
                }
              },
              "mappings": [],
              "thresholds": {
                "mode": "absolute",
                "steps": [
                  {
                    "color": "green",
                    "value": null
                  },
                  {
                    "color": "red",
                    "value": 1
                  }
                ]
              }
            },
            "overrides": []
          },
          "gridPos": {
            "h": 8,
            "w": 24,
            "x": 0,
            "y": 0
          },
          "id": 1,
          "options": {
            "legend": {
              "calcs": [],
              "displayMode": "list",
              "placement": "bottom",
              "showLegend": true
            },
            "tooltip": {
              "mode": "single",
              "sort": "none"
            }
          },
          "targets": [
            {
              "datasource": {
                "type": "prometheus",
                "uid": "PBFA97CFB590B2093"
              },
              "editorMode": "code",
              "expr": "ALERTS",
              "legendFormat": "{{alertname}}",
              "range": true,
              "refId": "A"
            }
          ],
          "title": "Active Alerts",
          "type": "timeseries"
        }
      ],
      "refresh": "5s",
      "schemaVersion": 38,
      "style": "dark",
      "tags": [],
      "templating": {
        "list": []
      },
      "time": {
        "from": "now-5m",
        "to": "now"
      },
      "timepicker": {},
      "timezone": "",
      "title": "Alert Dashboard",
      "uid": "alert-dashboard",
      "version": 1,
      "weekStart": ""
    }