name: CI-CD

on:
  push:
    branches: [ main ]
  pull_request:

jobs:
  build-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-go@v5
        with: { go-version: '1.22' }
      - run: go test ./... -coverprofile=coverage.out
      - run: go vet ./...
      - name: Security scan
        uses: securego/gosec@v3

  docker:
    needs: build-test
    runs-on: ubuntu-latest
    steps:
      - uses: docker/setup-qemu-action@v3
      - uses: docker/setup-buildx-action@v3
      - uses: docker/login-action@v3
        with: { registry: ghcr.io, username: ${{github.actor}}, password: ${{secrets.GITHUB_TOKEN}} }
      - run: docker buildx build --push \
              --tag ghcr.io/${{ github.repository }}/api:${{ github.sha }} .

  deploy:
    needs: docker
    runs-on: ubuntu-latest
    environment: dev
    steps:
      - uses: actions/checkout@v4
      - uses: azure/setup-helm@v4
      - run: helm upgrade --install api ./helm/chart \
              --set image.tag=${{ github.sha }} \
              --namespace dev --create-namespace